export {default as RvButton} from './Button.vue'
export {default as RvTabs} from './tab/Tabs.vue'
export {default as RvTabPane} from './tab/TabPane.vue'
export {default as RvIcon} from './Icon.vue'
export {default as RvDialog} from './Dialog.vue'
export {default as RvSwitch} from './Switch.vue'
export { openDialog as openDialog } from './openDialog'
